/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tvsAREBS.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 49.13]}>
        <mesh geometry={nodes.screen.geometry} material={nodes.screen.material} />
        <mesh geometry={nodes['TV-Mat'].geometry} material={materials.TVMat1} />
        <mesh geometry={nodes['TV-Mat2'].geometry} material={materials.TVMat2} />
      </group>
    </group>
  )
}

useGLTF.preload('/tvsAREBS.glb')
