/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import * as THREE from "three";
import { AudioAnalyser } from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useFrame } from "@react-three/fiber";
import { useLimiter, useModel } from "spacesvr";

type GLTFResult = GLTF & {
  nodes: {
    screen: THREE.Mesh;
    "TV-Mat": THREE.Mesh;
    "TV-Mat2": THREE.Mesh;
    "TV-Mat001": THREE.Mesh;
    "NEs-Mat": THREE.Mesh;
    "NEs-Mat1": THREE.Mesh;
    "NEs-Mat2": THREE.Mesh;
    "NEs-Mat3": THREE.Mesh;
  };
  materials: {
    ["Mat2"]: THREE.MeshStandardMaterial;
    ["Mat1"]: THREE.MeshStandardMaterial;
    ["Mat3"]: THREE.MeshStandardMaterial;
    ["Mat4"]: THREE.MeshStandardMaterial;
    ["TVMat1"]: THREE.MeshStandardMaterial;
    ["TVMat2"]: THREE.MeshStandardMaterial;
    Mat: THREE.MeshStandardMaterial;
  };
};

type ModelProps = JSX.IntrinsicElements["group"];

const fileURL =
  "https://d1htv66kutdwsl.cloudfront.net/a58e6db2-9ab4-418a-8298-fa5f55d90662/09c17d71-652e-473c-966c-3927fb011bcb.glb";

export function TV(props: ModelProps) {
  const { nodes, materials } = useModel(fileURL) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[10.53, 113.92, -83.61]}>
        <mesh
          geometry={nodes.screen.geometry}
          material={nodes.screen.material}
        />
        <mesh geometry={nodes["TV-Mat"].geometry} material={materials.TVMat1} />
        <mesh
          geometry={nodes["TV-Mat2"].geometry}
          material={materials.TVMat2}
        />
      </group>
      <group position={[3.54, 82.66, -27.28]}>
        <mesh geometry={nodes["NEs-Mat"].geometry} material={materials.Mat} />
        <mesh geometry={nodes["NEs-Mat1"].geometry} material={materials.Mat1} />
        <mesh geometry={nodes["NEs-Mat2"].geometry} material={materials.Mat2} />
        {/* <mesh geometry={nodes['NEs-Mat3'].geometry} material={materials.Mat3} /> */}
      </group>
    </group>
  );
}

useModel.preload(fileURL);
